version: 0.2
os: linux
files:
  - source: .
    destination: /var/www/html/school-sport-web
    file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/school-sport-web
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    type:
      - directory
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 664
    type:
      - file

hooks:
  ApplicationStart:
    - location: aws/application-start.sh
      timeout: 3600